version: "2.2"

x-uffizzi:
  ingress:
    service: web
    port: 3000
  continuous_preview:
    deploy_preview_when_pull_request_is_opened: true
    delete_preview_when_pull_request_is_closed: true
    share_to_github: true

services:
  web:
    build: .
    ports:
      - "3000:3000"
